---
-
  become: true
  hosts: webservers
  name: "config Web VM with Docker"
  tasks:
    -
      apt:
        force_apt_get: yes
        update_cache: yes
        name: docker.io
        state: present
      name: "Install docker.io  (state=present is optional)"
    -
      apt:
        name: python3-pip
        state: present
      name: "Install Python 3"
    -
      name: "Install Docker"
      pip:
        name: docker
        state: present
    -
      apt:
        name: apache2
        state: absent
      name: "Uninstall apache"
    -
      docker_container:
        image: cyberxsecurity/dvwa
        name: dvwa
        published_ports: "80:80"
        state: started
      name: "download and launch a docker web container"
    -
      name: "Enable docker service"
      systemd:
        enabled: true
        name: docker